
[features]
seeds = false
[programs.localnet]
gm_solana = "4RrUoq88TA3UnnrU347NGqkvvrsknv2psHXaZhsWtNDj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/gab-182/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
